export const SaleOrderConfig = [
    {key: 'product', label: '产品', width: '10%', type: 'text', options: []},
    {key: 'price', label: '价格', width: '10%', type: 'text', options: []},
    {key: 'order_date', label: '订单日期', width: '10%', type: 'text', options: []},
    {key: 'latest_shipment_date', label: '最晚发货日期', width: '10%', type: 'text', options: []},
    {key: 'customer', label: '客户', width: '10%', type: 'text', options: []},
    {key: 'shipping_country', label: '发货国家', width: '10%', type: 'text', options: []},
    {key: 'is_invoice_issued', label: '是否开票', width: '10%', type: 'text', options: []},
    {key: 'is_sample_order', label: '样品订单', width: '10%', type: 'text', options: []},
    {key: 'customer_shipping_fee', label: '客户运费', width: '10%', type: 'text', options: []},
    {key: 'owner_shipping_fee', label: '自己运费', width: '10%', type: 'text', options: []},
    {key: 'other_fee', label: '其他费用', width: '10%', type: 'text', options: []},
    {key: 'exchange_rate', label: '汇率', width: '10%', type: 'text', options: []},
    {key: 'sales_invoice', label: '下载发票', width: '10%', type: 'text', options: []},
    {key: 'description', label: '备注', width: '10%', type: 'text', options: []},
  ];