http://localhost:3000/api/user/list

###
http://localhost:3000/api/resource/list

###
http://localhost:3000/api/user/5plus/permission

###
POST http://localhost:3000/api/user
content-type: application/json

{
    "name": "test",
    "password": "123456"
}

###
POST http://localhost:3000/api/login
content-type: application/json

{
    "name": "test",
    "password": "123456"
}