@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjVwbHVzIiwiaWF0IjoxNjk0MzYwNDM2LCJleHAiOjE2OTQzNjQwMzZ9.V-_X8OVwC6rnjHcC5P-cM4eMXecQQwBdOA7sueQmG7w

### 查询客户列表
{{host}}/api/customers
token: {{token}}

### 新增客户
POST {{host}}/api/customers
Content-Type: application/json
token: {{token}}

{
    "name":"53p11121",
    "address":"Shengzhen,China", 
    "country": "china",
    "email":"wumingyong@gmail.com", 
    "phone":"166666666", 
    "other":"no"
}

### 用ID查询客户
{{host}}/api/customers/1
token: {{token}}

### 用ID更新客户
POST {{host}}/api/customers/1
Content-Type: application/json
token: {{token}}

{
    "name":"xieshu",
    "other":"no"
}

### 删除指定ID的客户
{{host}}/api/customers/delete/1
token: {{token}}