### 查询供应商列表
http://localhost:3000/api/suppliers

### 新增供应商
POST http://localhost:3000/api/suppliers
Content-Type: application/json

{
    "name":"53p1",
    "address":"Shengzhen,China", 
    "contact_name":"wumingyong", 
    "contact_email":"wumingyong@gmail.com", 
    "contact_phone":"166666666", 
    "other":"no"
}

### 用ID查询供应商
http://localhost:3000/api/suppliers/1

### 用ID更新供应商
POST http://localhost:3000/api/suppliers/2
Content-Type: application/json

{
    "name":"xieshu",
    "other":"no"
}

### 删除指定ID的供应商
http://localhost:3000/api/suppliers/delete/1