### 创建用户
POST http://localhost:3000/api/user
content-type: application/json

{
    "name": "csx",
    "password": "6789",
    "role": "Administrator"
}

### 删除用户
http://localhost:3000/api/user/delete/csx

### 修改用户
POST http://localhost:3000/api/user/xsc
content-type: application/json

{
    "password": "12345",
    "role": "Administrator"
}

### 查询用户
http://localhost:3000/api/user/list

###
http://localhost:3000/api/resource/list

###
POST http://localhost:3000/api/role/Purchaser
Content-Type: application/json

{
    "permissions":"10,20,21,22,23,'xsc'"
}

###
http://localhost:3000/api/role/list

###
http://localhost:3000/api/user/5plus/permission

###
http://localhost:3000/api/role/Administrator/permission

###
http://localhost:3000/api/role/Purchaser/permission

###
POST http://localhost:3000/api/user
content-type: application/json

{
    "name": "test",
    "password": "123456",
    "role": "Administrator"
}

###
POST http://localhost:3000/api/login
content-type: application/json

{
    "name": "test",
    "password": "123456"
}