@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjVwbHVzIiwiaWF0IjoxNjk0MzU4MDUzLCJleHAiOjE2OTQzNjE2NTN9.bcsgOL5j8VT2u4MMma0nUAxmSQUGptD0xh_JE-WGygE

### 创建用户
POST {{host}}/api/user
content-type: application/json
token: {{token}}

{
    "name": "csx",
    "password": "678910",
    "role": "Administrator"
}

### 删除用户
{{host}}/api/user/delete/csx
token: {{token}}

### 修改用户
POST {{host}}/api/user/xsc
content-type: application/json
token: {{token}}

{
    "password": "12345",
    "role": "Administrator"
}

### 查询用户
{{host}}/api/user/list
token: {{token}}

###
{{host}}/api/resource/list
token: {{token}}

###
POST {{host}}/api/role/Purchaser
Content-Type: application/json
token: {{token}}

{
    "permissions":"10,20,21,22,23,'xsc'"
}

###
{{host}}/api/role/list
token: {{token}}

###
{{host}}/api/user/5plus/permission
token: {{token}}

###
{{host}}/api/role/Administrator/permission
token: {{token}}

###
{{host}}/api/role/Purchaser/permission
token: {{token}}

###
POST {{host}}/api/user
content-type: application/json
token: {{token}}

{
    "name": "test",
    "password": "123456",
    "role": "Administrator"
}

###
POST {{host}}/api/login
content-type: application/json

{
    "name": "5plus",
    "password": "123456"
}